import {StyleSheet, Platform} from 'react-native';
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from 'react-native-responsive-screen';
import {normalize} from '../../helpers/helper';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'white',
    width: widthPercentageToDP('100%'),
  },

  imageBackground: {
    width: widthPercentageToDP('100%'),
    height: heightPercentageToDP('16%'),
    backgroundColor: 'black',
    borderBottomLeftRadius: normalize(27),
    borderBottomRightRadius: normalize(27),
  },
  imageBackgroundView: {
    width: widthPercentageToDP('100%'),
    height: heightPercentageToDP('16%'),

    borderBottomLeftRadius: normalize(27),
    borderBottomRightRadius: normalize(27),
  },
  longTouchable: {
    width: widthPercentageToDP('95%'),
    height: heightPercentageToDP('5%'),
    borderColor: '#B2B2B2',
    borderWidth: 1,
    borderRadius: normalize(30),
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: widthPercentageToDP('5%'),
    marginBottom: heightPercentageToDP('1%'),
  },
  shortTouchable: {
    width: widthPercentageToDP('46%'),
    height: heightPercentageToDP('5%'),
    borderColor: '#B2B2B2',
    borderWidth: 1,
    borderRadius: normalize(30),
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: widthPercentageToDP('5%'),
    marginBottom: heightPercentageToDP('1%'),
  },
  textStyle: {
    fontSize: normalize(14),
    color: 'black',
    marginLeft: widthPercentageToDP('3%'),
    width: widthPercentageToDP('50%'),
    textAlign: 'left',
  },
  searchView: {
    height: widthPercentageToDP('18.6%'),
    width: widthPercentageToDP('18.6%'),
    borderRadius: widthPercentageToDP('37.2%'),
    backgroundColor: '#F8C440',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    right: 25,
  },
  mainContainer: {
    width: widthPercentageToDP('95%'),
    alignItems: 'center',
    height: heightPercentageToDP('70%'),
    // borderTopLeftRadius: normalize(30),
    // borderTopRightRadius: normalize(30),
    // bottom: heightPercentageToDP('6%'),
    backgroundColor: 'white',
  },
  shadowBox: {
    width: widthPercentageToDP('86.5%'),
    height: heightPercentageToDP('25%'),
    backgroundColor: 'white',
    borderRadius: normalize(6),
    elevation: 5,
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: normalize(2),
    shadowOffset: {
      height: 1,
      width: 0,
    },
  },
  buttonStyle: {
    width: widthPercentageToDP('65%'),
    height: heightPercentageToDP('6%'),
    backgroundColor: '#F8C440',
    borderRadius: normalize(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: heightPercentageToDP('3%'),
    marginLeft: widthPercentageToDP('5.75%'),
  },
  addJetView: {
    height: widthPercentageToDP('15%'),
    width: widthPercentageToDP('15%'),
    borderRadius: widthPercentageToDP('30%'),
    backgroundColor: '#F8C440',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS == 'ios' ? heightPercentageToDP('0.5%') : null,
  },
  addContainer: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginTop: heightPercentageToDP('3%'),
    marginBottom: heightPercentageToDP('3%'),
  },
  addText: {
    marginRight: widthPercentageToDP('3%'),
    fontSize: normalize(16),
    color: 'black',
  },
  plusStyle: {
    color: 'white',
    fontSize: normalize(45),
  },
  jetStyle: {
    width: widthPercentageToDP('90%'),
    alignItems: 'center',
    height: heightPercentageToDP('18%'),
    flexDirection: 'row',
    marginBottom: heightPercentageToDP('3%'),
    marginTop: heightPercentageToDP('0.5%'),
    justifyContent: 'space-between',
    borderRadius: normalize(6),
    elevation: 5,
    shadowColor: '#000000',
    shadowOpacity: 0.5,
    shadowRadius: normalize(2),
    shadowOffset: {
      height: 0,
      width: 1,
    },
    borderLeftWidth: 0.5,
    borderRightWidth: 0.5,
    backgroundColor: 'white',
  },
});
