import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from 'react-native-responsive-screen';
import {normalize} from '../../helpers/helper';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'white',
    width: widthPercentageToDP('100%'),
  },

  imageBackground: {
    width: widthPercentageToDP('100%'),
    height: heightPercentageToDP('22%'),
    backgroundColor: 'black',
    borderBottomLeftRadius: normalize(27),
    borderBottomRightRadius: normalize(27),
  },
  imageBackgroundView: {
    width: widthPercentageToDP('100%'),
    height: heightPercentageToDP('22%'),

    borderBottomLeftRadius: normalize(27),
    borderBottomRightRadius: normalize(27),
  },
  longTouchable: {
    width: widthPercentageToDP('95%'),
    height: heightPercentageToDP('5%'),
    borderColor: '#B2B2B2',
    borderWidth: 1,
    borderRadius: normalize(30),
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: widthPercentageToDP('5%'),
    marginBottom: heightPercentageToDP('1%'),
  },
  shortTouchable: {
    width: widthPercentageToDP('46%'),
    height: heightPercentageToDP('5%'),
    borderColor: '#B2B2B2',
    borderWidth: 1,
    borderRadius: normalize(30),
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: widthPercentageToDP('5%'),
    marginBottom: heightPercentageToDP('1%'),
  },
  textStyle: {
    fontSize: normalize(14),
    color: 'black',
    marginLeft: widthPercentageToDP('3%'),
    width: widthPercentageToDP('50%'),
    textAlign: 'left',
  },
  searchView: {
    height: widthPercentageToDP('18.6%'),
    width: widthPercentageToDP('18.6%'),
    borderRadius: widthPercentageToDP('37.2%'),
    backgroundColor: '#F8C440',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    right: 25,
  },
  mainContainer: {
    width: widthPercentageToDP('95%'),
    alignItems: 'center',
    height: heightPercentageToDP('70%'),
    borderTopLeftRadius: normalize(30),
    borderTopRightRadius: normalize(30),
    bottom: heightPercentageToDP('6%'),
    backgroundColor: 'white',
  },
  shadowBox: {
    width: widthPercentageToDP('86.5%'),
    height: heightPercentageToDP('25%'),
    backgroundColor: 'white',
    borderRadius: normalize(6),
    elevation: 5,
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: normalize(2),
    shadowOffset: {
      height: 1,
      width: 0,
    },
  },
  buttonStyle: {
    width: widthPercentageToDP('65%'),
    height: heightPercentageToDP('6%'),
    backgroundColor: '#F8C440',
    borderRadius: normalize(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: heightPercentageToDP('3%'),
    alignSelf: 'center',
  },
  buttonStyleSmall: {
    width: widthPercentageToDP('32%'),
    height: heightPercentageToDP('6%'),
    backgroundColor: '#F8C440',
    borderRadius: normalize(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: heightPercentageToDP('3%'),
  },
  buttonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: widthPercentageToDP('5%'),
  },
});
